In [3]:
%matplotlib inline
import numpy as np
import pandas as pd

np.random.seed(1349)

## Statistics Exercises

1. How likely is it that you roll doubles when rolling two dice?

1. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

1. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

1. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

1. Compare Heights

    - Men have an average height of 178 cm and standard deviation of 8cm.
    - Women have a mean of 170, sd = 6cm.
    - If a man and woman are chosen at random, P(woman taller than man)?

1. When installing anaconda on a student's computer, there's a 1 in 250 chance
   that the download is corrupted and the installation fails. What are the odds
   that after having 50 students download anaconda, no one has an installation
   issue?  100 students?

    What is the probability that we observe an installation issue within the first
    150 students that download anaconda?

    How likely is it that 450 students all download anaconda without an issue?

1. There's a 70% chance on any given day that there will be at least one food
   truck at Travis Park. However, you haven't seen a food truck there in 3 days.
   How unlikely is this?

    How likely is it that a food truck will show up sometime this week?

1. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

#### 1. How likely is it that you roll doubles when rolling two dice?

In [1]:
#answer via probability
6/36
#(1,1) (2,2) (3,3) (4,4) (5,5) (6,6)

0.16666666666666666

In [5]:
#answer via simulation
n_trials = nrows= 10_000 #number of times we're going to roll
n_dice = ncols= 2 #number of dice

rolls = np.random.choice([1,2,3,4,5,6], n_trials * n_dice).reshape(nrows,ncols)
rolls

array([[5, 1],
       [6, 5],
       [2, 4],
       ...,
       [3, 2],
       [2, 6],
       [4, 4]])

In [6]:
rolls = pd.DataFrame(rolls)
rolls.apply(lambda x:min(x) == max(x), 1).mean()

0.1679

#### #2 If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [10]:
Heads =1
Tails = 0
coin=[Heads, Tails]

In [11]:
n_trials = n_rows = 10_000 #number of tries
n_coins = n_cols = 8 #number of coins

In [12]:
coin_flip= np.random.choice(coin, (n_rows, ncols))
sum_trial = coin_flip.sum(axis=1)

In [13]:
exactly_three = sum_trial == 3 #this means that its exactly equal to 3

In [15]:
rate_exactly_three = exactly_three.mean() #this will give us the average times that it was exactly 3
rate_exactly_three

0.0

#### #2 TEACHER SOLUTION WALK THROUGH

In [74]:
n_rows= 1_000_000
n_col = 8
heads =1
tails=0
flips= np.random.choice([heads, tails], size =(n_rows, n_cols))

In [75]:
flips

array([[1, 0, 0, ..., 1, 0, 1],
       [1, 1, 0, ..., 1, 0, 1],
       [1, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 1, 1]])

In [77]:
num_heads = flips.sum(axis=1)
calculated_prob=(num_heads == 3).mean()

In [78]:
calculated_prob

0.0

In [ ]:
#More than 3

In [79]:
calculated_prob=(num_heads >= 3).mean()

In [80]:
calculated_prob

1.0

#### #3 There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [82]:
# ANSWER with probability
# 3 webdev per 1 dS == 1/4 classes is DS == 25% of classes are DS
# 2 billboards
# odds of both having a data science student on it
# 25% chance per billboard * 2 billboards = 1/8
(1/4) * (1/4)

0.0625

In [17]:
#ANSWER with simulation
p_WDev = 0.75 #3/4 are WDev classes
p_DS = 0.25 #1/4 are DS classes
n_trails = n_rows = 10_000 #number of attempts
n_billboards = n_cols= 2 #number of billboards

In [76]:
data= np.random.random((n_rows, n_cols))

In [81]:
DS_billboard = data < p_DS #chances of DS on billboard = random being less than 0.25
DS_billboard

array([[False, False,  True, ..., False, False,  True],
       [False, False, False, ..., False, False, False],
       [False,  True, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [ True,  True, False, ..., False, False, False],
       [False, False, False, ...,  True, False, False]])

In [20]:
(DS_billboard.sum(axis=1)==2).mean() #this gives the average of how many times DS student being on billboard is equal to 2

0.0624

#### #4 Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [21]:
# 1.5-4.5 puchases a day (average 3)
# 17 packages every monday
#probability to buy one on Friday
#Mon:17 - (1.5-4.5) = 15.5-12.5 =day 1 prob = 100%
#Tues: 15-12.5 - (1.5-4.5)= 13.5-8 = day 2 prob 100% 
#Wed:13.5-8 - (1.5-4.5)= 12-3.5 = day 3 prob 100%
#Thurs: 12-3.5 - (1.5-4.5)= 10.5-(-1) = day 4, could have 10.5 or -1 left / 50% chance
#Friday: 10.5 -(-1) - (1.5-4.5) = 9-(-5.5)= day 4, could have 9 or -5.5/ 50% chance

In [22]:
n_packages = 17 #number of poptarts
n_days = 5 #number of days (M-F days of class)
n_trials = n_rows = 10_000 #number of attempts

In [25]:
packages = np.round(np.random.normal(3,1.5, (n_rows, n_days)))
packages
#this is acknowledging that 3 is the average but the range is +-1.5

array([[4., 3., 2., 2., 7.],
       [2., 3., 2., 3., 5.],
       [6., 4., 2., 3., 3.],
       ...,
       [1., 5., 0., 4., 3.],
       [4., 3., 1., 4., 6.],
       [5., 1., 2., 2., 2.]])

In [26]:
package_purchased = np.where(packages < 0,0,packages)
package_purchased

array([[4., 3., 2., 2., 7.],
       [2., 3., 2., 3., 5.],
       [6., 4., 2., 3., 3.],
       ...,
       [1., 5., 0., 4., 3.],
       [4., 3., 1., 4., 6.],
       [5., 1., 2., 2., 2.]])

In [28]:
all_packages = package_purchased.sum(axis=1)
all_packages

array([18., 15., 18., ..., 13., 18., 12.])

In [29]:
package_left_friday = all_packages < 17
package_left_friday

array([False,  True, False, ...,  True, False,  True])

In [31]:
prob_left_friday = package_left_friday.mean()
prob_left_friday

0.6728

#### # 4 TEACHER PROBLEM WORK THROUGH

In [83]:
pop_avg = 3
pop_std = 1.5
n_cols= 5
n_rows = 1_000_000
simulated_consumed_poptarts= np.random.normal(pop_avg, pop_std,(n_rows, n_days))

In [84]:
simulated_consumed_poptarts

array([[ 3.44693733,  4.42889231,  2.42817599,  5.3524548 ,  2.95095361],
       [ 1.45939835,  3.81778348,  3.57960384,  1.07970233,  3.23244665],
       [ 3.43070855,  1.06081584,  4.52303446,  3.91044364,  3.61662124],
       ...,
       [ 4.33266582,  4.67680225,  5.04369341,  0.26036987,  4.26304244],
       [ 2.94865386,  1.11381255,  3.88711793,  0.30990011,  5.49360944],
       [ 1.54844103,  5.50277617, -0.1872898 ,  2.37429534,  0.7291635 ]])

In [85]:
calculated_prob = (simulated_consumed_poptarts.sum(axis=1) <17).mean()
calculated_prob

0.725086

#### #5 Compare Heights
- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- If a man and woman are chosen at random, P(woman taller than man)?

In [32]:
#men = 178cm/sd:8cm
#women = 170cm/sd: 6cm

In [33]:
#height = random(height given, sd, number of attempts)
M_height = np.random.normal(178,8,10000)
W_height = np.random.normal(170,6,10000)

In [54]:
heights = pd.DataFrame({'Men': M_height, 'Women': W_height})
heights

Men       Women
0     169.513620  179.625977
1     160.476830  171.224513
2     177.608048  168.791929
3     171.701525  174.254429
4     168.325663  169.016157
...          ...         ...
9995  175.917130  173.641106
9996  194.453919  169.369293
9997  185.316274  166.697751
9998  178.601290  169.742002
9999  157.177490  158.467458

[10000 rows x 2 columns]

In [55]:
difference = heights['Women'] - heights ['Men'] #male height - female height
difference

0       10.112357
1       10.747683
2       -8.816119
3        2.552903
4        0.690494
          ...    
9995    -2.276024
9996   -25.084626
9997   -18.618523
9998    -8.859288
9999     1.289968
Length: 10000, dtype: float64

In [56]:
women_taller = difference >0 
women_taller

0        True
1        True
2       False
3        True
4        True
        ...  
9995    False
9996    False
9997    False
9998    False
9999     True
Length: 10000, dtype: bool

In [57]:
rate_women_taller = women_taller.mean() #gives the rate of women being taller
rate_women_taller

0.2101

In [ ]:
#### #5 TEACHER WALK THROUGH

In [87]:
men_avg= 178
men_std=8
women_avg=170
women_std=6

In [88]:
s_men = np.random.normal(men_avg, men_std, 1_000_000)

In [89]:
s_women = np.random.normal(women_avg, women_std, 1_000_000)

In [91]:
calculated_prob = (s_women > s_men).mean()
calculated_prob

0.211955

#### #6 When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. 
- What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?
- What is the probability that we observe an installation issue within the first 150 students that download anaconda?
- How likely is it that 450 students all download anaconda without an issue?

In [43]:
# prob_fail = 1/250
# 50 students == 0 fails
# 100 students == 0 fails
# 150 students >= 1 fail
# 450 students == 0 fails

In [44]:
p_fails = 1/250
n_installs = n_cols = 150
n_trials = n_rows = 10_000

In [46]:
anaconda_installs = np.random.random((n_rows,n_cols))

In [48]:
fails = anaconda_installs < p_fails 
fails

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [51]:
sum_fail_installs = fails.sum(axis=1) > 0
sum_fail_installs

array([False,  True, False, ..., False,  True, False])

In [53]:
rate_fail_install = sum_fail_installs.mean()
rate_fail_install

0.4504

In [ ]:
# 50 people

In [ ]:
#450 people

#### #6 TEACHER WALKTHROUGH

In [ ]:
# 50 installs

In [ ]:
nrows= 1_000_000
n_cols= 50
conda_fails= 1
success = 0
prob_fail= 1/250

In [92]:
prob_fail

0.004

In [93]:
installs = np.random.random((nrows,n_cols))

In [94]:
installs < prob_fail

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       ...,
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [95]:
((installs < prob_fail).sum(axis=1)== 0).mean()

0.9801

In [ ]:
#100 installs

In [96]:
nrows= 1_000_000
n_cols= 100
conda_fails= 1
success = 0
prob_fail= 1/250

In [97]:
installs = np.random.random((nrows,n_cols))

In [98]:
installs < prob_fail

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [99]:
((installs < prob_fail).sum(axis=1)== 0).mean()

0.669975

In [ ]:
# 150 installs at least 1 fail

In [104]:
nrows= 1_000_000
n_cols= 450
conda_fails= 1
success = 0
prob_fail= 1/250

In [105]:
installs = np.random.random((nrows,n_cols))

In [106]:
installs < prob_fail

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [107]:
((installs < prob_fail).sum(axis=1)> 0).mean()

0.835353

In [ ]:
# 450 installs

In [108]:
nrows= 1_000_000
n_cols= 450
conda_fails= 1
success = 0
prob_fail= 1/250

In [101]:
installs = np.random.random((nrows,n_cols))

In [102]:
installs < prob_fail

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [103]:
((installs < prob_fail).sum(axis=1)== 0).mean()

0.164398

#### #7 There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [ ]:
n_rows= 1_000_000
n_cols= 3
food_truck=1
no_truck=0

In [109]:
data= np.random.random((n_rows,n_cols))

In [110]:
truck_prob = 0.7

In [111]:
((data < truck_prob).sum(axis=1)==0).mean()

0.0

In [ ]:
# on last 2 days of week

In [ ]:
n_rows= 1_000_000
n_cols= 2 #2 days left in week
food_truck=1
no_truck=0
truck_prob = 0.7

In [112]:
lunch_days = np.random.random((n_rows,n_cols))

In [115]:
calculated_prob= ((lunch_days < truck_prob).sum(axis=1) >0).mean()
calculated_prob

1.0

#### #8 If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [ ]:
#365 days in a year
#23 people in class
#prob of same birthday

In [119]:
outcomes = range(0, 365) #number of days in a year
n_trails= 23 #number of students
n_simulated= 1_000_000 

In [ ]:
classrooms= np.random.choice(outcomes, size=(n_simulated, n_trials))