In [1]:
%matplotlib inline
import numpy as np
import pandas as pd

np.random.seed(1349)

## Statistics Exercises

1. How likely is it that you roll doubles when rolling two dice?

1. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

1. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

1. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

1. Compare Heights

    - Men have an average height of 178 cm and standard deviation of 8cm.
    - Women have a mean of 170, sd = 6cm.
    - If a man and woman are chosen at random, P(woman taller than man)?

1. When installing anaconda on a student's computer, there's a 1 in 250 chance
   that the download is corrupted and the installation fails. What are the odds
   that after having 50 students download anaconda, no one has an installation
   issue?  100 students?

    What is the probability that we observe an installation issue within the first
    150 students that download anaconda?

    How likely is it that 450 students all download anaconda without an issue?

1. There's a 70% chance on any given day that there will be at least one food
   truck at Travis Park. However, you haven't seen a food truck there in 3 days.
   How unlikely is this?

    How likely is it that a food truck will show up sometime this week?

1. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

#### 1. How likely is it that you roll doubles when rolling two dice?

In [2]:
#answer via probability
6/36
#(1,1) (2,2) (3,3) (4,4) (5,5) (6,6)

0.16666666666666666

In [3]:
#answer via simulation
n_trials = nrows= 10_000 #number of times we're going to roll
n_dice = ncols= 2 #number of dice

rolls = np.random.choice([1,2,3,4,5,6], n_trials * n_dice).reshape(nrows,ncols)
rolls

array([[3, 2],
       [5, 3],
       [4, 4],
       ...,
       [3, 2],
       [3, 5],
       [2, 2]])

In [4]:
rolls = pd.DataFrame(rolls)
rolls.apply(lambda x:min(x) == max(x), 1).mean()

0.1596

#### #2 If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [5]:
Heads =1
Tails = 0
coin=[Heads, Tails]

In [6]:
n_trials = n_rows = 10_000 #number of tries
n_coins = n_cols = 8 #number of coins

In [7]:
coin_flip= np.random.choice(coin, (n_rows, ncols))
sum_trial = coin_flip.sum(axis=1)

In [8]:
exactly_three = sum_trial == 3 #this means that its exactly equal to 3

In [9]:
rate_exactly_three = exactly_three.mean() #this will give us the average times that it was exactly 3
rate_exactly_three

0.0

#### #2 TEACHER SOLUTION WALK THROUGH

In [10]:
n_rows= 1_000_000
n_col = 8
heads =1
tails=0
flips= np.random.choice([heads, tails], size =(n_rows, n_cols))

In [11]:
flips

array([[1, 0, 0, ..., 0, 0, 1],
       [1, 0, 1, ..., 1, 0, 1],
       [0, 0, 1, ..., 0, 1, 1],
       ...,
       [1, 1, 0, ..., 1, 1, 1],
       [1, 0, 0, ..., 1, 0, 1],
       [0, 1, 1, ..., 1, 0, 1]])

In [12]:
num_heads = flips.sum(axis=1)
calculated_prob=(num_heads == 3).mean()

In [13]:
calculated_prob

0.218928

In [14]:
#More than 3

In [15]:
calculated_prob=(num_heads >= 3).mean()

In [16]:
calculated_prob

0.85603

#### #3 There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [17]:
# ANSWER with probability
# 3 webdev per 1 dS == 1/4 classes is DS == 25% of classes are DS
# 2 billboards
# odds of both having a data science student on it
# 25% chance per billboard * 2 billboards = 1/8
(1/4) * (1/4)

0.0625

In [18]:
#ANSWER with simulation
p_WDev = 0.75 #3/4 are WDev classes
p_DS = 0.25 #1/4 are DS classes
n_trails = n_rows = 10_000 #number of attempts
n_billboards = n_cols= 2 #number of billboards

In [19]:
data= np.random.random((n_rows, n_cols))

In [20]:
DS_billboard = data < p_DS #chances of DS on billboard = random being less than 0.25
DS_billboard

array([[False, False],
       [ True, False],
       [False, False],
       ...,
       [ True, False],
       [False, False],
       [False, False]])

In [21]:
(DS_billboard.sum(axis=1)==2).mean() #this gives the average of how many times DS student being on billboard is equal to 2

0.0616

#### #4 Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [22]:
# 1.5-4.5 puchases a day (average 3)
# 17 packages every monday
#probability to buy one on Friday
#Mon:17 - (1.5-4.5) = 15.5-12.5 =day 1 prob = 100%
#Tues: 15-12.5 - (1.5-4.5)= 13.5-8 = day 2 prob 100% 
#Wed:13.5-8 - (1.5-4.5)= 12-3.5 = day 3 prob 100%
#Thurs: 12-3.5 - (1.5-4.5)= 10.5-(-1) = day 4, could have 10.5 or -1 left / 50% chance
#Friday: 10.5 -(-1) - (1.5-4.5) = 9-(-5.5)= day 4, could have 9 or -5.5/ 50% chance

In [23]:
n_packages = 17 #number of poptarts
n_days = 5 #number of days (M-F days of class)
n_trials = n_rows = 10_000 #number of attempts

In [24]:
packages = np.round(np.random.normal(3,1.5, (n_rows, n_days)))
packages
#this is acknowledging that 3 is the average but the range is +-1.5

array([[ 3.,  4.,  4.,  5.,  3.],
       [ 3.,  1.,  4.,  2.,  4.],
       [ 3.,  5.,  3.,  3.,  2.],
       ...,
       [ 3.,  3.,  5.,  2.,  3.],
       [-0.,  2.,  4.,  3.,  5.],
       [ 3.,  4.,  4.,  6.,  2.]])

In [25]:
package_purchased = np.where(packages < 0,0,packages)
package_purchased

array([[ 3.,  4.,  4.,  5.,  3.],
       [ 3.,  1.,  4.,  2.,  4.],
       [ 3.,  5.,  3.,  3.,  2.],
       ...,
       [ 3.,  3.,  5.,  2.,  3.],
       [-0.,  2.,  4.,  3.,  5.],
       [ 3.,  4.,  4.,  6.,  2.]])

In [26]:
all_packages = package_purchased.sum(axis=1)
all_packages

array([19., 14., 16., ..., 16., 14., 19.])

In [27]:
package_left_friday = all_packages < 17
package_left_friday

array([False,  True,  True, ...,  True,  True, False])

In [28]:
prob_left_friday = package_left_friday.mean()
prob_left_friday

0.673

#### # 4 TEACHER PROBLEM WORK THROUGH

In [29]:
pop_avg = 3
pop_std = 1.5
n_cols= 5
n_rows = 1_000_000
simulated_consumed_poptarts= np.random.normal(pop_avg, pop_std,(n_rows, n_days))

In [30]:
simulated_consumed_poptarts

array([[1.93834181, 3.75038676, 2.4075977 , 1.92056846, 1.89742193],
       [3.75912825, 3.1006546 , 2.79885517, 3.3314    , 2.0283801 ],
       [5.4869528 , 4.19134434, 2.28812109, 1.1017987 , 1.89620818],
       ...,
       [3.16739544, 4.14280843, 2.37444856, 4.73127214, 3.47785702],
       [4.05230326, 4.62849836, 5.16748513, 5.70607992, 3.46096734],
       [3.28999605, 3.29885121, 4.3258163 , 3.00450105, 2.75325065]])

In [31]:
calculated_prob = (simulated_consumed_poptarts.sum(axis=1) <17).mean()
calculated_prob

0.724643

#### #5 Compare Heights
- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- If a man and woman are chosen at random, P(woman taller than man)?

In [32]:
#men = 178cm/sd:8cm
#women = 170cm/sd: 6cm

In [33]:
#height = random(height given, sd, number of attempts)
M_height = np.random.normal(178,8,10000)
W_height = np.random.normal(170,6,10000)

In [34]:
heights = pd.DataFrame({'Men': M_height, 'Women': W_height})
heights

Men       Women
0     178.405087  174.654519
1     183.211322  162.683081
2     185.181752  172.214135
3     176.147762  166.227237
4     192.348996  174.024506
...          ...         ...
9995  175.739903  168.719332
9996  166.983095  171.278414
9997  170.157626  170.780917
9998  182.937924  166.278568
9999  192.057324  174.270859

[10000 rows x 2 columns]

In [35]:
difference = heights['Women'] - heights ['Men'] #male height - female height
difference

0       -3.750569
1      -20.528241
2      -12.967617
3       -9.920525
4      -18.324490
          ...    
9995    -7.020571
9996     4.295319
9997     0.623291
9998   -16.659356
9999   -17.786465
Length: 10000, dtype: float64

In [36]:
women_taller = difference >0 
women_taller

0       False
1       False
2       False
3       False
4       False
        ...  
9995    False
9996     True
9997     True
9998    False
9999    False
Length: 10000, dtype: bool

In [37]:
rate_women_taller = women_taller.mean() #gives the rate of women being taller
rate_women_taller

0.2128

In [38]:
#### #5 TEACHER WALK THROUGH

In [39]:
men_avg= 178
men_std=8
women_avg=170
women_std=6

In [40]:
s_men = np.random.normal(men_avg, men_std, 1_000_000)

In [41]:
s_women = np.random.normal(women_avg, women_std, 1_000_000)

In [42]:
calculated_prob = (s_women > s_men).mean()
calculated_prob

0.212517

#### #6 When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. 
- What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?
- What is the probability that we observe an installation issue within the first 150 students that download anaconda?
- How likely is it that 450 students all download anaconda without an issue?

In [43]:
# prob_fail = 1/250
# 50 students == 0 fails
# 100 students == 0 fails
# 150 students >= 1 fail
# 450 students == 0 fails

In [44]:
p_fails = 1/250
n_installs = n_cols = 150
n_trials = n_rows = 10_000

In [45]:
anaconda_installs = np.random.random((n_rows,n_cols))

In [46]:
fails = anaconda_installs < p_fails 
fails

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [47]:
sum_fail_installs = fails.sum(axis=1) > 0
sum_fail_installs

array([ True,  True,  True, ..., False, False, False])

In [48]:
rate_fail_install = sum_fail_installs.mean()
rate_fail_install

0.4589

In [49]:
# 50 people

In [50]:
#450 people

#### #6 TEACHER WALKTHROUGH

In [51]:
# 50 installs

In [52]:
nrows= 1_000_000
n_cols= 50
conda_fails= 1
success = 0
prob_fail= 1/250

In [53]:
prob_fail

0.004

In [54]:
installs = np.random.random((nrows,n_cols))

In [55]:
installs < prob_fail

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [56]:
((installs < prob_fail).sum(axis=1)== 0).mean()

0.818092

In [57]:
#100 installs

In [58]:
nrows= 1_000_000
n_cols= 100
conda_fails= 1
success = 0
prob_fail= 1/250

In [59]:
installs = np.random.random((nrows,n_cols))

In [60]:
installs < prob_fail

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False,  True],
       [False, False, False, ..., False, False, False]])

In [61]:
((installs < prob_fail).sum(axis=1)== 0).mean()

0.66961

In [62]:
# 150 installs at least 1 fail

In [63]:
nrows= 1_000_000
n_cols= 450
conda_fails= 1
success = 0
prob_fail= 1/250

In [ ]:
installs = np.random.random((nrows,n_cols))

In [ ]:
installs < prob_fail

In [ ]:
((installs < prob_fail).sum(axis=1)> 0).mean()

In [ ]:
# 450 installs

In [ ]:
nrows= 1_000_000
n_cols= 450
conda_fails= 1
success = 0
prob_fail= 1/250

In [ ]:
installs = np.random.random((nrows,n_cols))

In [ ]:
installs < prob_fail

In [ ]:
((installs < prob_fail).sum(axis=1)== 0).mean()

#### #7 There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [ ]:
n_rows= 1_000_000
n_cols= 3
food_truck=1
no_truck=0

In [ ]:
data= np.random.random((n_rows,n_cols))

In [ ]:
truck_prob = 0.7

In [ ]:
((data < truck_prob).sum(axis=1)==0).mean()

In [ ]:
# on last 2 days of week

In [ ]:
n_rows= 1_000_000
n_cols= 2 #2 days left in week
food_truck=1
no_truck=0
truck_prob = 0.7

In [ ]:
lunch_days = np.random.random((n_rows,n_cols))

In [ ]:
calculated_prob= ((lunch_days < truck_prob).sum(axis=1) >0).mean()
calculated_prob

#### #8 If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [ ]:
#365 days in a year
#23 people in class
#prob of same birthday

In [ ]:
#23 students in the class

In [ ]:
outcomes = range(0, 365) #number of days in a year
n_trials= 23 #number of students
n_simulated= 1_000_000 

In [ ]:
classrooms= np.random.choice(outcomes, size=(n_simulated, n_trials))

In [ ]:
len(np.unique(classrooms[3]))

In [ ]:
list_of_twin_birthdays = [len(np.unique(classrooms[n])) for n in range(0, n_simulated-1) if len(np.unique(classrooms[n])) <23]

In [ ]:
prop_twin_bdays = len(list_of_twin_birthdays) / n_simulated

In [ ]:
prop_twin_bdays 

In [ ]:
# 20 students per class

In [ ]:
outcomes = range(0, 365) #number of days in a year
n_trials= 20 #number of students
n_simulated= 1_000_000 

In [ ]:
classrooms= np.random.choice(outcomes, size=(n_simulated, n_trials))

In [ ]:
len(np.unique(classrooms[3]))

In [ ]:
list_of_twin_birthdays = [len(np.unique(classrooms[n])) for n in range(0, n_simulated-1) if len(np.unique(classrooms[n])) <20]

In [ ]:
prop_twin_bdays = len(list_of_twin_birthdays) / n_simulated

In [ ]:
prop_twin_bdays 

In [ ]:
# 40 students per class

In [ ]:
outcomes = range(0, 365) #number of days in a year
n_trials= 40 #number of students
n_simulated= 1_000_000 

In [ ]:
classrooms= np.random.choice(outcomes, size=(n_simulated, n_trials))

In [ ]:
len(np.unique(classrooms[3]))

In [ ]:
list_of_twin_birthdays = [len(np.unique(classrooms[n])) for n in range(0, n_simulated-1) if len(np.unique(classrooms[n])) <40]

In [ ]:
prop_twin_bdays = len(list_of_twin_birthdays) / n_simulated

In [ ]:
prop_twin_bdays 